### ISSUE TITLE
crash on launch: java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

### ISSUE THREAD

**Issue by satyr2b** [TrvsF/wurstplus-two#35]
this causes me to crash every time i launch minecraft with wurst+2

java.lang.ClassNotFoundException: The specified class 'me.zero.alpine.fork.bus.EventBus' was not found)

java.lang.ClassNotFoundException: The specified class 'me.zero.alpine.fork.event.type.Cancellable' was not found)

**Comment by satyr2b** [comment]
running wurst+2 standalone comes up with this fatal error:
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

**Comment by satyr2b** [comment]
crash log:

[23:26:24] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:26:24] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:26:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:26:24] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[23:26:24] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64
[23:26:24] [main/INFO] [FML]: Searching C:\Users\soop\AppData\Roaming\.minecraft\mods for mods
[23:26:24] [main/INFO] [FML]: Searching C:\Users\soop\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[23:26:24] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Vtuber client-1.0.jar
[23:26:24] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:26:24] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[23:26:24] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:26:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:26:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:26:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:26:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:26:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[23:26:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:26:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by notperry1** [comment]
Don't remove the orgs library if your on mac/linux genius.

**Comment by satyr2b** [comment]
1. I found out that this is yet another issue with salhack
2. im using windows
