### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by salsasl** [TrvsF/wurstplus-two#41]
My game crashes whenever I press tab. Not sure why.  Here's the crash report: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  WurstplusMixinLoader (WurstPlusTwo (1).jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 11/5/20 8:26 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: toIndex = 255
	at java.util.ArrayList.subListRangeCheck(Unknown Source)
	at java.util.ArrayList.subList(Unknown Source)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.redirect$subListHook$zzm000(SourceFile:519)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.func_175249_a(SourceFile:83)
	at net.minecraftforge.client.GuiIngameForge.renderPlayerList(GuiIngameForge.java:844)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:201)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.subListRangeCheck(Unknown Source)
	at java.util.ArrayList.subList(Unknown Source)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.redirect$subListHook$zzm000(SourceFile:519)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.func_175249_a(SourceFile:83)
	at net.minecraftforge.client.GuiIngameForge.renderPlayerList(GuiIngameForge.java:844)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:201)

-- Affected level --
Details:
	Level name: MpServer
	All players: 6 total; [EntityPlayerSP['Rayfarer'/5040071, l='MpServer', x=0.50, y=121.50, z=0.50], EntityOtherPlayerMP['Flqry'/5038947, l='MpServer', x=0.03, y=121.50, z=-5.40], EntityOtherPlayerMP['GayTrap'/4990990, l='MpServer', x=-2.70, y=3.00, z=1.70], EntityOtherPlayerMP['0Neb'/5039886, l='MpServer', x=17.19, y=4.02, z=-7.34], EntityOtherPlayerMP['oggy___'/4938681, l='MpServer', x=-2.70, y=3.00, z=1.31], EntityOtherPlayerMP['DkeRee'/5032402, l='MpServer', x=18.30, y=2.00, z=-9.30]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,125,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 61951 game time, 1710000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 47 total; [EntityPlayerSP['Rayfarer'/5040071, l='MpServer', x=0.50, y=121.50, z=0.50], EntityOtherPlayerMP['Flqry'/5038947, l='MpServer', x=0.03, y=121.50, z=-5.40], EntityEnderCrystal['entity.EnderCrystal.name'/5005005, l='MpServer', x=9.50, y=3.00, z=-44.50], EntityOtherPlayerMP['GayTrap'/4990990, l='MpServer', x=-2.70, y=3.00, z=1.70], EntityOtherPlayerMP['0Neb'/5039886, l='MpServer', x=17.19, y=4.02, z=-7.34], EntityOtherPlayerMP['oggy___'/4938681, l='MpServer', x=-2.70, y=3.00, z=1.31], EntityOtherPlayerMP['DkeRee'/5032402, l='MpServer', x=18.30, y=2.00, z=-9.30], EntityEnderCrystal['entity.EnderCrystal.name'/5035083, l='MpServer', x=21.50, y=3.00, z=-32.50], EntityEnderCrystal['entity.EnderCrystal.name'/5024709, l='MpServer', x=36.50, y=5.00, z=37.50], EntityEnderCrystal['entity.EnderCrystal.name'/5024710, l='MpServer', x=34.50, y=5.00, z=36.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005120, l='MpServer', x=36.50, y=5.00, z=-8.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005123, l='MpServer', x=35.50, y=3.00, z=-9.50], EntityEnderCrystal['entity.EnderCrystal.name'/5008350, l='MpServer', x=-61.50, y=3.00, z=13.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005016, l='MpServer', x=7.50, y=5.00, z=-45.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005018, l='MpServer', x=10.50, y=5.00, z=-42.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005008, l='MpServer', x=7.50, y=4.00, z=-40.50], EntityOtherPlayerMP['DkeRee'/5032402, l='MpServer', x=18.30, y=2.00, z=-9.30], EntityEnderCrystal['entity.EnderCrystal.name'/5005038, l='MpServer', x=12.50, y=5.00, z=-44.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005156, l='MpServer', x=39.50, y=4.00, z=-9.50], EntityOtherPlayerMP['Flqry'/5038947, l='MpServer', x=0.03, y=121.50, z=-5.40], EntityEnderCrystal['entity.EnderCrystal.name'/5005048, l='MpServer', x=12.50, y=4.00, z=-42.50], EntityEnderCrystal['entity.EnderCrystal.name'/5037178, l='MpServer', x=1.50, y=5.00, z=24.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005040, l='MpServer', x=10.50, y=5.00, z=-44.50], EntityEnderCrystal['entity.EnderCrystal.name'/5009266, l='MpServer', x=-41.50, y=5.00, z=20.50], EntityOtherPlayerMP['GayTrap'/4990990, l='MpServer', x=-2.70, y=3.00, z=1.70], EntityOtherPlayerMP['0Neb'/5039886, l='MpServer', x=17.19, y=4.02, z=-7.34], EntityEnderCrystal['entity.EnderCrystal.name'/5004934, l='MpServer', x=2.50, y=4.00, z=-34.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004928, l='MpServer', x=2.50, y=4.00, z=-36.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004956, l='MpServer', x=3.50, y=5.00, z=-38.50], EntityEnderCrystal['entity.EnderCrystal.name'/5000477, l='MpServer', x=26.50, y=1.00, z=59.50], EntityEnderCrystal['entity.EnderCrystal.name'/5034653, l='MpServer', x=-61.50, y=3.00, z=-5.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004954, l='MpServer', x=2.50, y=5.00, z=-40.50], EntityEnderCrystal['entity.EnderCrystal.name'/5040144, l='MpServer', x=-3.50, y=4.00, z=0.50], EntityEnderCrystal['entity.EnderCrystal.name'/5040046, l='MpServer', x=20.50, y=3.00, z=-8.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004965, l='MpServer', x=5.50, y=5.00, z=-43.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004960, l='MpServer', x=3.50, y=4.00, z=-42.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004321, l='MpServer', x=-6.50, y=5.00, z=-34.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004962, l='MpServer', x=1.50, y=4.00, z=-42.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004963, l='MpServer', x=7.50, y=4.00, z=-42.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005117, l='MpServer', x=36.50, y=4.00, z=-6.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004861, l='MpServer', x=-3.50, y=3.00, z=-33.50], EntityOtherPlayerMP['oggy___'/4938681, l='MpServer', x=-2.70, y=3.00, z=1.31], EntityEnderCrystal['entity.EnderCrystal.name'/5005118, l='MpServer', x=39.50, y=5.00, z=-7.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005112, l='MpServer', x=34.50, y=4.00, z=-12.50], EntityEnderCrystal['entity.EnderCrystal.name'/5004856, l='MpServer', x=-4.50, y=5.00, z=-35.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005114, l='MpServer', x=38.50, y=4.00, z=-12.50], EntityEnderCrystal['entity.EnderCrystal.name'/5005110, l='MpServer', x=36.50, y=4.00, z=-15.50]]
	Retry entities: 0 total; []
	Server brand: FlameCord <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 426254656 bytes (406 MB) / 679477248 bytes (648 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                                  | Signature                                |
	|:------ |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | wurstplus | 1.0          | WurstPlusTwo (1).jar                    | None                                     |

	Loaded coremods (and transformers): 
WurstplusMixinLoader (WurstPlusTwo (1).jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.23' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.23, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

**Comment by CynicalMuffin** [comment]
Nope dosent happen for me try seeing if you have another mod that might cause it

**Comment by Darkwoodz** [comment]
its a feature

**Comment by ya-ilya** [comment]
https://github.com/colmalle/WurstPlusTwo-fix - use this version

**Comment by TrvsF** [comment]
should be fixed
